apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oauth2-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --ssl-insecure-skip-verify=true
        - --auth-logging=true
        - --cookie-secure=true
        - --cookie-samesite=lax
        - --cookie-refresh=4m0s
        - --cookie-expire=4h
        - --cookie-name=_oauth2_proxy_istio_ingressgateway
        - --pass-access-token=true
        - --set-authorization-header=true
        - --email-domain=*
        - --http-address=0.0.0.0:4180
        - --upstream=static://200
        - --skip-provider-button=true
        - --pass-authorization-header=true
        - --set-xauthrequest=true
        - --pass-access-token=true
        - --oidc-groups-claim=groups
        - --show-debug-on-error=true
        # - --login-url=$OIDC_AUTH_ENDPOINT
        # - --redeem-url=$OIDC_TOKEN_ENDPOINT
        # - --profile-url=$OIDC_PROFILE_URL
        # - --oidc-issuer-url=$OIDC_ISSUER_URL
        # - --oidc-jwks-url=$OIDC_JWKS_URI
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: OAUTH2_PROXY_CLIENT_ID
              name: oauth2-proxy
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: OAUTH2_PROXY_CLIENT_SECRET
              name: oauth2-proxy
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              key: OAUTH2_PROXY_COOKIE_SECRET
              name: oauth2-proxy
        - name: OAUTH2_PROXY_LOGIN_URL
          valueFrom:
            secretKeyRef:
              key: OIDC_AUTH_ENDPOINT
              name: oauth2-proxy
        - name: OAUTH2_PROXY_REDEEM_URL
          valueFrom:
            secretKeyRef:
              key: OIDC_TOKEN_ENDPOINT
              name: oauth2-proxy
        - name: OAUTH2_PROXY_PROFILE_URL
          valueFrom:
            secretKeyRef:
              key: OIDC_PROFILE_URL
              name: oauth2-proxy
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              key: OIDC_ISSUER_URL
              name: oauth2-proxy
        - name: OAUTH2_PROXY_OIDC_JWKS_URL
          valueFrom:
            secretKeyRef:
              key: OIDC_JWKS_URI
              name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: IfNotPresent
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

